import type { Metadata } from 'next'
import './globals.css'
import Footer from '@/components/Footer'
import Privacy from '@/components/Privacy'
import Work_with_us from '@/components/Work_with_us'
import Vacancies from '@/components/Vacancies'

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
        <Privacy />
        <Work_with_us />
        <Vacancies />
        <Footer />
      </body>
    </html>
  )
}
